---
title: "simple_case"
author: "Hedi"
date: "20 août 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
#loading inputs
questions <- read.csv("./input/survey.csv", stringsAsFactors = F)
choices <- read.csv("./input/choices.csv", stringsAsFactors = F)
data <- load_data(file = "./input/data.csv")
sampling_frame <- load_samplingframe(file = "./input/sampling_frame.csv")
questionnaire <- load_questionnaire(data = data,
                                    questions = questions,
                                    choices = choices,
                                    choices.label.column.to.use = "label::English (en)")
weights <-map_to_weighting(sampling.frame = sampling_frame,
                           data.stratum.column = "strata.names",
                           sampling.frame.population.column = "population",
                           sampling.frame.stratum.column = "strata.names",
                           data = data)

#CASE_direct_reporting_categorical_ 
case_directreporting <- map_to_case(hypothesis.type = "direct_reporting",
                    dependent.var.type = "categorical")

case_directreporting_result<-map_to_result(data = data,
                           dependent.var = "push_factors",
                           case = case,
                           weighting = weights,
                           questionnaire = questionnaire)

#CASE_group_difference_categorical_categorical
case_group_difference <- map_to_case(hypothesis.type = "group_difference",
                    dependent.var.type = "categorical",
                    independent.var.type = "categorical")
case_group_difference_result<-map_to_result(data = data,
                      dependent.var = "push_factors",
                      independent.var = "displacement_status",
                      case = case,
                      weighting = weights,
                      questionnaire = questionnaire)
```

