source("code/data_merge_functions.R")

# Make sure to source hte first 27 lines of preliminary weighted analysis to get
# data, quesitonnaire, choices and weighting function

data <- mutate_if(data, is.character, na_if, "")

dm_data <- data %>%
  mutate(fcs = (cereals * 2) + (legumes * 3) + veggies + fruits + (meat * 4) + (dairy * 4) + (fats * 0.5) + (sugar * 0.5),
         fcs_category = case_when(
           fcs <= 28 ~ "poor",
           fcs > 28 & fcs <= 42 ~ "borderline",
           fcs > 42 ~ "acceptable"
         ),
         rcsi = less_expensive_quality + (borrow_relatives * 2) + reduce_number_meals + (reduce_adult * 3) + shrink_meals,
         rcsi_category = case_when(
           rcsi <= 3 ~ "low",
           rcsi > 3 & rcsi <= 9 ~ "medium",
           rcsi > 9 ~ "high"
         ),
         permanent_job_adult = rowSums(select(., permanent_job_adult_male, permanent_job_adult_female), na.rm = T),
         temporary_job_adult = rowSums(select(., temporary_job_adult_male, temporary_job_adult_female), na.rm = T),
         daily_labour_job_adult = rowSums(select(., daily_labour_adult_male, daily_labour_adult_female), na.rm = T),
         gvt_payroll_job_adult = rowSums(select(., gvt_payroll_adult_male, gvt_payroll_adult_female), na.rm = T),
         permanent_job_minor = rowSums(select(., permanent_job_minor_male, permanent_job_minor_female), na.rm = T),
         temporary_job_minor = rowSums(select(., temporary_job_minor_male, temporary_job_minor_female), na.rm = T),
         daily_labour_job_minor = rowSums(select(., daily_labour_minor_male, daily_labour_minor_female), na.rm = T),
         cash_coping_stress = rowSums(select(., 
                                             sold_nonproductive_hh_assets,
                                             spent_savings,
                                             borrowed_purchased_oncredit_food,
                                             reduced_expenditures_essential_nfi) %>%
                                        mutate_all(~ .x %in% c("already_exhausted_this_coping_strategy", "yes")),
                                      na.rm = T),
         cash_coping_crisis = rowSums(select(., 
                                             sold_productive_hh_assets,
                                             borrowed_money,
                                             reduced_expenditures_health_education,
                                             took_additional_job) %>%
                                        mutate_all(~ .x %in% c("already_exhausted_this_coping_strategy", "yes")),
                                      na.rm = T),
         cash_coping_emergency = rowSums(select(., 
                                                begging,
                                                adult_accepting_degrading_illegal_work,
                                                minor_accepting_degrading_illegal_work,
                                                child_marriage) %>%
                                           mutate_all(~ .x %in% c("already_exhausted_this_coping_strategy", "yes")),
                                         na.rm = T),
         cash_coping = case_when(
           cash_coping_emergency > 0 ~ "emergency",
           cash_coping_crisis > 0 ~ "crisis",
           cash_coping_stress > 0 ~ "stress"
         ),
         nfi_need = rowSums(select(., mattresses:construction_materials_equipment,
                                   -ends_with("_other")) %>%
                              mutate_all(~ .x %in% c("hh_doesnt_own_it", "hh_owns_it_need_more")),
                            na.rm = T),
         nfi_need = ifelse(nfi_need >= 8, "has_nfi_need", "no_need"),
         bottle_fed_child = ifelse(fed_children_bottled_milk > 0 , "bottle_fed_child", "no_bottle_feeding"),
         unable_vaccinate = ifelse(nb_children_notable_get_vaccination > 0, "unable_vaccinate", "able_vaccinate"),
         nb_youth_male_edu = ifelse(nb_youth_male == 0, NA, nb_youth_male), ######## these vars allow for weighting on enrollment data
         nb_children_male_edu = ifelse(nb_children_male == 0, NA, nb_children_male),
         nb_youth_female_edu = ifelse(nb_youth_female == 0, NA, nb_youth_female),
         nb_children_female_edu = ifelse(nb_children_female == 0, NA, nb_children_female),
         enrolled_school_female_15_17_edu = ifelse(enrolled_school_female_15_17 == 0, NA, enrolled_school_female_15_17), ## These vars allow for weighting attendance data
         enrolled_school_female_6_14_edu = ifelse(enrolled_school_female_6_14 == 0, NA, enrolled_school_female_6_14),
         enrolled_school_male_15_17_edu = ifelse(enrolled_school_male_15_17 == 0, NA, enrolled_school_male_15_17),
         enrolled_school_male_6_14_edu = ifelse(enrolled_school_male_6_14 == 0, NA, enrolled_school_male_6_14),
         document_needs = str_concat("not_everyone_has_legal_doc",
                                     property_docs,
                                     family_books,
                                     certificate_nationality,
                                     passport,
                                     national_identifier,
                                     national_idcard,
                                     residence_certificate,
                                     birth_certificate,
                                     other_docs),
         returnee_issues = str_concat("yes",
                                      house_occupied,
                                      inability_prove_legal_ownership,
                                      hostility_from_local_community,
                                      lack_security_area,
                                      parts_house_property_destroyed,
                                      missing_valuables_house_property,
                                      inability_move_freely,
                                      basic_services_hh_nolonger_working,
                                      basic_services_community_nolonger_working,
                                      mobilephone_network_nolonger_working,
                                      other_problem_faced),
         returnee_issues = ifelse(is.na(returnee_issues) & displacement_status == "returnee",
                                  "",
                                  returnee_issues)) %>%
  rowwise() %>%
  mutate(no_daily_difficulty = sum(no_difficulty_carrying_activities_female_adults,
                                   no_difficulty_carrying_activities_female_infant,
                                   no_difficulty_carrying_activities_female_children,
                                   no_difficulty_carrying_activities_female_youth,
                                   no_difficulty_carrying_activities_female_elderly,
                                   no_difficulty_carrying_activities_male_adults,
                                   no_difficulty_carrying_activities_male_infant,
                                   no_difficulty_carrying_activities_male_children,
                                   no_difficulty_carrying_activities_male_youth,
                                   no_difficulty_carrying_activities_male_elderly,
                                   na.rm = T),
         minor_daily_difficulty = sum(minor_difficulties_carrying_activities_female_adults,
                                      minor_difficulties_carrying_activities_female_infant,
                                      minor_difficulties_carrying_activities_female_children,
                                      minor_difficulties_carrying_activities_female_youth,
                                      minor_difficulties_carrying_activities_female_elderly,
                                      minor_difficulties_carrying_activities_male_adults,
                                      minor_difficulties_carrying_activities_male_infant,
                                      minor_difficulties_carrying_activities_male_children,
                                      minor_difficulties_carrying_activities_male_youth,
                                      minor_difficulties_carrying_activities_male_elderly,
                                      na.rm = T),
         daily_needs_assistance = sum(some_difficulties_carrying_activities_female_adults,
                                      some_difficulties_carrying_activities_female_infant,
                                      some_difficulties_carrying_activities_female_children,
                                      some_difficulties_carrying_activities_female_youth,
                                      some_difficulties_carrying_activities_female_elderly,
                                      some_difficulties_carrying_activities_male_adults,
                                      some_difficulties_carrying_activities_male_infant,
                                      some_difficulties_carrying_activities_male_children,
                                      some_difficulties_carrying_activities_male_youth,
                                      some_difficulties_carrying_activities_male_elderly,
                                      alot_difficulties_carrying_activities_female_adults,
                                      alot_difficulties_carrying_activities_female_infant,
                                      alot_difficulties_carrying_activities_female_children,
                                      alot_difficulties_carrying_activities_female_youth,
                                      alot_difficulties_carrying_activities_female_elderly,
                                      alot_difficulties_carrying_activities_male_adults,
                                      alot_difficulties_carrying_activities_male_infant,
                                      alot_difficulties_carrying_activities_male_children,
                                      alot_difficulties_carrying_activities_male_youth,
                                      alot_difficulties_carrying_activities_male_elderly,
                                      cannot_carry_activities_female_adults,
                                      cannot_carry_activities_female_infant,
                                      cannot_carry_activities_female_children,
                                      cannot_carry_activities_female_youth,
                                      cannot_carry_activities_female_elderly,
                                      cannot_carry_activities_male_adults,
                                      cannot_carry_activities_male_infant,
                                      cannot_carry_activities_male_children,
                                      cannot_carry_activities_male_youth,
                                      cannot_carry_activities_male_elderly,
                                      na.rm = T),
         total_assistance = sum(no_daily_difficulty, minor_daily_difficulty, daily_needs_assistance)) %>%
  ungroup
